package com.instamngmt.entity;

public enum NotificationType {
    POST_PUBLISHED,
    POST_FAILED,
    POST_RETRYING,
    RATE_LIMIT_WARNING,
    CIRCUIT_BREAKER_ACTIVE,
    TOKEN_EXPIRED,
    TOKEN_REFRESH_FAILED,
    ACCOUNT_CONNECTED,
    ACCOUNT_DISCONNECTED,
    BULK_IMPORT_COMPLETED,
    SYSTEM_ALERT
}
